site_name: AU915 LoRaWAN
theme:
  name: material
markdown_extensions:
  - footnotes
  - tables
  - pymdownx.highlight:
    anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.smartsymbols
  